# Development overrides for docker-compose.yml
# Usage: docker compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Development backend with volume mounting and hot reload
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      target: base  # Use the base stage for development
    volumes:
      - ./src/backend:/app/src/backend
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - /app/node_modules  # Anonymous volume to preserve node_modules
    environment:
      NODE_ENV: development
    command: ["dumb-init", "yarn", "dev:backend"]
    ports:
      - "3001:3001"
      - "9229:9229"  # Node.js debugger port

  # Development frontend with volume mounting and hot reload
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      target: build  # Use build stage for development
    volumes:
      - ./src/frontend:/app/src/frontend
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - /app/node_modules  # Anonymous volume to preserve node_modules
    environment:
      VITE_API_URL: http://localhost:3001
    command: ["yarn", "dev:frontend"]
    ports:
      - "5173:5173"

  # Override nginx for development
  nginx:
    ports:
      - "8080:80"  # Use different port to avoid conflicts
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro