// Service exports for easy importing
export { RecommendationEngine } from './RecommendationEngine'
export { UserBuilder } from './UserBuilder'
export { ContentSimilarity } from './ContentSimilarity'
export { CollaborativeFilter } from './CollaborativeFilter'
export { NLPSimilarity } from './NLPSimilarity'
export { TrendAnalysis } from './TrendAnalysis'
export { DiversityEngine } from './DiversityEngine'
export { RealtimeEngine } from './RealtimeEngine'